/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3af31349-840c-46f2-8025-8055e5707c93",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3cqRB1EgU",
    "aws_user_pools_web_client_id": "p90s7fu27827nq9n8li93m8s1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://f4vn6xaqcjenpeipqqtgl6qhay.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
